# This makefile aims at procesing all file
# First, TestDict is dictionary that should be generated by root cling.
# Then, all .o file must be generated in order to reduce compile time
# .so library is final aim if no specific excutable file is needed.

# SOURCE = BoardBuffer.cpp BoardsManager.cpp CombineData.cpp Configure.cpp OneGroup.cpp Loop.cpp TPrimaryData.cpp TCombinedData.cpp FileManager.cpp TDetectorInfo.cpp mppc.cpp

USERROOT = $(HOME)
PWD = `pwd`

DIR_INC = ./include
DIR_SRC = ./src
DIR_OBJ = ./obj
DIR_BIN = ./bin
DIR_LIB = ./lib

# Search all .cpp files in this directory(main.cpp) and src directory
SRC = $(wildcard ${DIR_SRC}/*.cpp)
# Search all .h files in include directroy
HEADERPRE = $(wildcard ${DIR_INC}/*.h)
HEADER = ${subst ${DIR_INC}/LinkDef.h, ,$(HEADERPRE)}
# substitute all .cpp in $(SRC) with .o, and add related directory path
OBJ = $(patsubst %.cpp,${DIR_OBJ}/%.o,$(notdir ${SRC}) )


# OBJ = BoardBuffer.o BoardsManager.o CombineData.o Configure.o OneGroup.o Loop.o TPrimaryData.o TCombinedData.o FileManager.o TDetectorInfo.o mppc.o GetPosition.o
# HEADER = BoardBuffer.h BoardsManager.h CombineData.h Configure.h OneGroup.h Loop.h TPrimaryData.h TCombinedData.h FileManager.h TDetectorInfo.h mppc.h GetPosition.h



CXXFLAGS = -g -Wall -I${DIR_INC} -I. `root-config --cflags`
CXXLIBS = `root-config --libs` -lSpectrum -L$(USERROOT)/lib 


LIB = ImagingAlgorithm
LIBFULL = $(patsubst %,${DIR_LIB}/lib%.so,$(LIB))

DIR_LINK = ./lkdef
LINKDEF = ${DIR_INC}/LinkDef.h
DICTCXX = ${DIR_LINK}/$(LIB)Dict.cxx


# Define uninstall path
UNINSTALLHEADER = $(patsubst %.h,${HOME}/include/${LIB}/%.h,$(notdir ${HEADER}))
UNINSTALLLIB = $(patsubst %.so,${HOME}/lib/%.so,$(notdir ${LIBFULL}))



Excutable = test read treetest treeread ProcessOrigin ReadData DrawSignal GetResult ReadOrigin TestThreshold


$(LIBFULL): $(OBJ) $(DICTCXX)
	@echo "####################################################"
	@echo Generating lib: $@
	@echo ----------------------------------------------------
	@`root-config --cxx`	-fPIC	-shared	-o	$@	$(OBJ)	$(DICTCXX) $(CXXFLAGS) $(CXXLIBS)
	@echo "####################################################"
	@echo 


${DIR_OBJ}/%.o: ${DIR_SRC}/%.cpp ${DIR_INC}/%.h
	@echo "####################################################"
	@echo Generating: $@
	@echo ----------------------------------------------------
	@`root-config --cxx `	-o	$@	-c	$<	-fPIC $(CXXFLAGS)
	@echo "####################################################"
	@echo 


$(DICTCXX): $(HEADER)   $(LINKDEF)
	@echo "####################################################"
	@echo rootcling generating $@
	@echo ----------------------------------------------------
	-@mkdir $(DIR_LINK)
	@rootcling	-f	$@	-c	$(HEADER)
	@cp $(DIR_LINK)/*pcm $(PWD)
	@echo "####################################################"
	@echo 




clean:
	-rm obj/*.o lib/*.so lkdef/* bin/*
distclean:
	-rm obj/*.o lib/*.so lkdef/* bin/*
	-rm *.root *.pdf $(Excutable) *Dict* filelist


test:  test.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB) $(CXXFLAGS) $(CXXLIBS)

# Stat scattering angle for every event
CheckAngle:  CheckAngle.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB) $(CXXFLAGS) $(CXXLIBS)

# Draw graph of specific data
DrawGraph:  DrawGraph.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB) $(CXXFLAGS) $(CXXLIBS)

# Verify distribution of original data, including combined 3D point, incident angle, scattering angle
VerifyOriginData:  VerifyOriginData.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB) $(CXXFLAGS) $(CXXLIBS)

# Read Resolution origin file, process geant4 simulation file
ReadResolution:  ReadResolution.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB) $(CXXFLAGS) $(CXXLIBS)




all: $(Excutable)

install: $(LIBFULL)
	@echo Copying lib and headers to user directory
	-@mkdir ~/lib ~/include/${LIB}/
	-@cp $(LIBFULL) ~/lib/
	-@cp $(HEADER) ~/include/${LIB}/

uninstall:
	@echo Uninstalling from ${HOME}/lib/ and ${HOME}/include/${LIB}/
	-@rm ${UNINSTALLHEADER}
	-@rm ${UNINSTALLLIB}